public class HttptHeaders {

//  HEADERS
    public static final String HEADER_CONTENT_TYPE = 'Content-Type';
    public static final String HEADER_AUTHORIZATION = 'Authorization';
    public static final String HEADER_SET_COOKIE =  'Set-Cookie';
    public static final String HEADER_ACCEPT =  'Accept';

//  APPLICATION TYPES
    public static final String APPLICATION_TYPE_JSON = 'application/json';
    public static final String APPLICATION_TYPE_WWW = 'application/x-www-form-urlencoded';
    public static final String APPLICATION_TYPE_JSON_UTF8 = 'application/json;charset=UTF-8';
    public static final String UTF_8 = 'UTF-8';

    private HttptHeaders() {
    }
}